import { defineConfig } from "tinacms";

const branch = process.env.HEAD || process.env.VERCEL_GIT_COMMIT_REF || "main";
const recipeProductOptions = [
  { label: "Castanya torrada", value: "castanya-torrada" },
  { label: "Farina de castanya", value: "farina-castanya" },
  { label: "Secallona", value: "secallona" },
  { label: "Flocs de castanya", value: "flocs-castanya" },
];

export default defineConfig({
  branch,
  clientId: process.env.TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,

  build: {
    outputFolder: "admin",
    publicFolder: "src", // Ensure this matches your Eleventy input directory
  },
  media: {
    tina: {
      // Keep Tina-managed media in the same folder the site already serves as /assets/images/...
      mediaRoot: "assets/images",
      publicFolder: "src",
    },
  },
  schema: {
    collections: [
      {
        name: "blog",
        label: "Blog Posts",
        path: "src/blog/posts",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "description",
            label: "Description",
            required: true,
          },
          {
            type: "datetime",
            name: "date",
            label: "Publication Date",
            required: true,
          },
          {
            type: "string",
            name: "displayDate",
            label: "Display Date",
          },
          {
            type: "string",
            name: "readingTimeValue",
            label: "Reading Time Value",
          },
          { type: "image", name: "image", label: "Featured Image" },
          { type: "string", name: "imageAlt", label: "Image Alt Text" },
          { type: "string", name: "seoTitle", label: "SEO Title" },
          {
            type: "string",
            name: "seoDescription",
            label: "SEO Description",
            ui: { component: "textarea" },
          },
          { type: "image", name: "seoImage", label: "SEO Image" },
          { type: "string", name: "tags", label: "Tags", list: true },
          { type: "boolean", name: "featured", label: "Featured Post" },
          {
            type: "string",
            name: "quote",
            label: "Pull Quote",
            ui: { component: "textarea" },
          },
          {
            type: "string",
            name: "quoteAuthor",
            label: "Pull Quote Author",
          },
          { type: "rich-text", name: "body", label: "Body", isBody: true },
        ],
        ui: {
          // document._sys.filename is standard, but ensure your 11ty routes match
          router: ({ document }) => `/blog/${document._sys.filename}`,
        },
      },
      {
        name: "products",
        label: "Products",
        path: "src/shop/products",
        format: "md",
        ui: {
          router: ({ document }) => `/shop/products/${document._sys.filename}/`,
          defaultItem: () => ({
            layout: "product",
            currency: "EUR",
            priceLabel: "Des de 0,00 €",
            ingredientsLabel: "INGREDIENTS",
            gallery: [],
            formatLabel: "Selecciona format",
            formats: [{ label: "Format 1", sku: "sku-1", price: 0 }],
            highlights: [],
            detailLabel: "DESCRIPCIO",
            detailNotes: [],
            ctaLabel: "AFEGIR A LA CISTELLA",
            ctaHref: "/shop/cart/",
            category: "elaborats-de-castanyes",
            consumptionMoments: ["cuinar"],
            dietTags: [],
            homepageTags: [],
            featured: false,
          }),
        },
        fields: [
          {
            type: "string",
            name: "layout",
            label: "Layout",
            required: true,
            ui: {
              component: "hidden",
            },
          },
          {
            type: "string",
            name: "title",
            label: "Product Name",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "tagline",
            label: "Tagline",
            required: true,
          },
          {
            type: "string",
            name: "category",
            label: "Shop Category",
            required: true,
            options: [
              { label: "Castanyes", value: "castanyes" },
              {
                label: "Elaborats de castanyes",
                value: "elaborats-de-castanyes",
              },
              { label: "Cremes", value: "cremes" },
              { label: "Dolços", value: "dolcos" },
              { label: "Begudes", value: "begudes" },
              { label: "Mels", value: "mels" },
              { label: "Packs", value: "packs" },
            ],
          },
          {
            type: "string",
            name: "consumptionMoments",
            label: "Moment de consum",
            list: true,
            options: [
              { label: "Per picar i compartir", value: "picar-compartir" },
              { label: "Per cuinar", value: "cuinar" },
              { label: "Moments dolços", value: "moments-dolcos" },
              { label: "Regals i detalls", value: "regals-detalls" },
            ],
          },
          {
            type: "string",
            name: "dietTags",
            label: "Dietes i intoleràncies",
            list: true,
            options: [
              { label: "Vegà", value: "vega" },
              { label: "Sense gluten", value: "sense-gluten" },
              { label: "Sense sucres afegits", value: "sense-sucres-afegits" },
            ],
          },
          {
            type: "string",
            name: "homepageTags",
            label: "Homepage tags",
            list: true,
            options: [
              { label: "Estrella", value: "estrella" },
              { label: "Pack regalo", value: "pack-regalo" },
            ],
          },
          {
            type: "number",
            name: "price",
            label: "Price",
            required: true,
          },
          {
            type: "string",
            name: "priceLabel",
            label: "Price label",
          },
          {
            type: "string",
            name: "sku",
            label: "Default SKU",
          },
          {
            type: "string",
            name: "currency",
            label: "Currency",
          },
          {
            type: "string",
            name: "availability",
            label: "Availability note",
            required: true,
          },
          {
            type: "string",
            name: "ingredientsLabel",
            label: "Ingredients label",
            required: true,
          },
          {
            type: "string",
            name: "ingredients",
            label: "Ingredients",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "image",
            name: "image",
            label: "Main image",
            required: true,
          },
          {
            type: "string",
            name: "description",
            label: "Short description",
            ui: { component: "textarea" },
            required: true,
          },
          { type: "string", name: "imageAlt", label: "Main image alt text" },
          { type: "string", name: "seoTitle", label: "SEO Title" },
          {
            type: "string",
            name: "seoDescription",
            label: "SEO Description",
            ui: { component: "textarea" },
          },
          { type: "image", name: "seoImage", label: "SEO Image" },
          {
            type: "object",
            name: "gallery",
            label: "Thumbnail gallery",
            list: true,
            fields: [
              { type: "image", name: "image", label: "Image", required: true },
            ],
          },
          {
            type: "string",
            name: "formatLabel",
            label: "Format select label",
            required: true,
          },
          {
            type: "object",
            name: "formats",
            label: "Format options",
            list: true,
            required: true,
            fields: [
              {
                type: "string",
                name: "label",
                label: "Label",
                required: true,
              },
              {
                type: "string",
                name: "sku",
                label: "SKU",
                required: true,
              },
              {
                type: "number",
                name: "price",
                label: "Price",
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "shippingNote",
            label: "Shipping note",
            required: true,
          },
          {
            type: "object",
            name: "highlights",
            label: "Highlights",
            list: true,
            fields: [
              { type: "string", name: "text", label: "Text", required: true },
            ],
          },
          {
            type: "string",
            name: "detailLabel",
            label: "Detail section label",
            required: true,
          },
          {
            type: "object",
            name: "detailNotes",
            label: "Detail notes",
            list: true,
            fields: [
              { type: "string", name: "text", label: "Text", required: true },
            ],
          },
          {
            type: "string",
            name: "ctaLabel",
            label: "CTA label",
            required: true,
          },
          {
            type: "string",
            name: "ctaHref",
            label: "CTA link",
            required: true,
          },
          {
            type: "boolean",
            name: "featured",
            label: "Featured Product",
          },
          {
            type: "rich-text",
            name: "body",
            label: "Detailed Description",
            isBody: true,
          },
        ],
      },
      {
        name: "visits",
        label: "Visites Page",
        path: "src/_data/visits",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              {
                type: "image",
                name: "image",
                label: "Hero Image",
                required: true,
              },
              {
                type: "string",
                name: "imageAlt",
                label: "Hero Image Alt Text",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Hero Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Hero Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "Hero Button Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "Hero Button Link",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "activitiesIntro",
            label: "Activities Intro",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "banner",
            label: "Bottom Banner",
            fields: [
              {
                type: "image",
                name: "image",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "imageAlt",
                label: "Background Image Alt Text",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Banner Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Banner Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "buttonLabel",
                label: "Button Label",
                required: true,
              },
              {
                type: "string",
                name: "buttonHref",
                label: "Button Link",
                required: true,
              },
            ],
          },
        ],
      },
      {
        name: "visitActivities",
        label: "Visit Activities",
        path: "src/visits/activities",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "number",
            name: "order",
            label: "Order",
            required: true,
          },
          {
            type: "string",
            name: "permalink",
            label: "Permalink",
            required: true,
          },
          {
            type: "image",
            name: "cardImage",
            label: "Card Image",
            required: true,
          },
          {
            type: "string",
            name: "cardImageAlt",
            label: "Card Image Alt Text",
            required: true,
          },
          {
            type: "string",
            name: "cardDescription",
            label: "Card Description",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "image",
            name: "heroImage",
            label: "Hero Image",
            required: true,
          },
          {
            type: "string",
            name: "heroImageAlt",
            label: "Hero Image Alt Text",
            required: true,
          },
          {
            type: "string",
            name: "galleryButtonLabel",
            label: "Gallery Button Label",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrompt",
            label: "Reservation Prompt",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrimaryLabel",
            label: "Primary Reservation Button Label",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrimaryLink",
            label: "Primary Reservation Button Link",
            required: true,
          },
          {
            type: "string",
            name: "whatsappLink",
            label: "WhatsApp Link",
          },
          {
            type: "string",
            name: "emailAddress",
            label: "Email Address",
          },
          {
            type: "string",
            name: "phoneNumber",
            label: "Phone Number",
          },
          {
            type: "string",
            name: "bookingHighlights",
            label: "Booking Highlights",
            list: true,
          },
          {
            type: "number",
            name: "personsMin",
            label: "Persons (Min)",
            required: true,
          },
          {
            type: "number",
            name: "personsMax",
            label: "Persons (Max)",
            required: true,
          },
          {
            type: "string",
            name: "duration",
            label: "Duration",
            required: true,
          },
          {
            type: "string",
            name: "priceFrom",
            label: "Price From",
            required: true,
          },
          {
            type: "string",
            name: "priceNote",
            label: "Price Note",
            required: true,
          },
          {
            type: "string",
            name: "difficulty",
            label: "Difficulty",
            required: true,
          },
          {
            type: "string",
            name: "kidFriendly",
            label: "Kid Friendly",
            required: true,
          },
          {
            type: "string",
            name: "languages",
            label: "Languages",
            required: true,
          },
          {
            type: "string",
            name: "overviewIntro",
            label: "Overview Intro",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "object",
            name: "itinerary",
            label: "Itinerary",
            list: true,
            fields: [
              {
                type: "string",
                name: "time",
                label: "Time",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "description",
                label: "Description",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "pricing",
            label: "Pricing",
            list: true,
            fields: [
              {
                type: "number",
                name: "group",
                label: "Group Size",
                required: true,
              },
              {
                type: "string",
                name: "price",
                label: "Price",
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "includedServices",
            label: "Included Services",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "string",
            name: "meetingPoint",
            label: "Meeting Point",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "string",
            name: "additionalInfo",
            label: "Additional Info",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "object",
            name: "experienceHighlightsSection",
            label: "Adventure Highlights Section",
            fields: [
              {
                type: "string",
                name: "eyebrow",
                label: "Eyebrow",
              },
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Intro",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "object",
                name: "items",
                label: "Cards",
                list: true,
                fields: [
                  {
                    type: "image",
                    name: "image",
                    label: "Card Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "title",
                    label: "Card Title",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "text",
                    label: "Card Text",
                    ui: { component: "textarea" },
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "reviewsSection",
            label: "Reviews Section",
            fields: [
              {
                type: "string",
                name: "eyebrow",
                label: "Eyebrow",
              },
              {
                type: "string",
                name: "title",
                label: "Title",
              },
              {
                type: "string",
                name: "ratingLabel",
                label: "Rating Label",
                required: true,
              },
              {
                type: "string",
                name: "ratingValue",
                label: "Rating Value",
              },
              {
                type: "string",
                name: "sourceLabel",
                label: "Source Label",
              },
              {
                type: "object",
                name: "reviews",
                label: "Reviews",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "quote",
                    label: "Quote",
                    ui: { component: "textarea" },
                    required: true,
                  },
                  {
                    type: "string",
                    name: "author",
                    label: "Author",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "date",
                    label: "Date",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "avatar",
                    label: "Avatar",
                  },
                  {
                    type: "string",
                    name: "avatarAlt",
                    label: "Avatar Alt Text",
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "gallery",
            label: "Gallery",
            list: true,
            fields: [
              {
                type: "image",
                name: "image",
                label: "Image",
                required: true,
              },
              {
                type: "string",
                name: "alt",
                label: "Image Alt Text",
                required: true,
              },
            ],
          },
          {
            type: "rich-text",
            name: "body",
            label: "General Description Body",
            isBody: true,
          },
        ],
        ui: {
          router: ({ document }) =>
            document?.permalink || `/visits/${document._sys.filename}/`,
        },
      },
      {
        name: "recipes",
        label: "Receptes",
        path: "src/gastronomic/receptes/recipes",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Titol",
            isTitle: true,
            required: true,
          },
          {
            type: "number",
            name: "order",
            label: "Ordre",
            required: true,
          },
          {
            type: "string",
            name: "permalink",
            label: "Permalink",
            required: true,
          },
          {
            type: "string",
            name: "listingSections",
            label: "Seccions del llistat",
            list: true,
            options: [
              { label: "Fonaments gastronomics", value: "foundations" },
              { label: "L'art de la castanyada", value: "homeTraditions" },
              { label: "Els classics", value: "classics" },
              { label: "Cuina saludable", value: "healthy" },
              { label: "Receptes dolces", value: "sweet" },
              { label: "Remeis", value: "remedies" },
            ],
            required: true,
          },
          {
            type: "image",
            name: "image",
            label: "Imatge principal",
            required: true,
          },
          {
            type: "string",
            name: "imageAlt",
            label: "Text alternatiu de la imatge",
            required: true,
          },
          {
            type: "string",
            name: "summary",
            label: "Resum",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "string",
            name: "author",
            label: "Autor",
            required: true,
          },
          {
            type: "string",
            name: "origin",
            label: "Origen o ubicacio",
            required: true,
          },
          {
            type: "string",
            name: "time",
            label: "Temps",
            required: true,
          },
          {
            type: "string",
            name: "difficulty",
            label: "Dificultat",
            required: true,
          },
          {
            type: "string",
            name: "ingredientsLabel",
            label: "Etiqueta ingredients",
            required: true,
          },
          {
            type: "string",
            name: "ingredients",
            label: "Ingredients",
            list: true,
            required: true,
          },
          {
            type: "string",
            name: "downloadPdfLabel",
            label: "Text boto PDF",
            required: true,
          },
          {
            type: "boolean",
            name: "pdfEnabled",
            label: "Activar descarrega PDF",
            required: true,
          },
          {
            type: "object",
            name: "steps",
            label: "Passos",
            list: true,
            fields: [
              {
                type: "string",
                name: "title",
                label: "Titol del pas",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Text del pas",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "secretTitle",
            label: "Titol del secret",
            required: true,
          },
          {
            type: "object",
            name: "relatedProductsSection",
            label: "Productes relacionats",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Titol de la seccio",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Text introductori",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "products",
                label: "Productes",
                list: true,
                options: recipeProductOptions,
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "secretQuote",
            label: "Text del secret",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "rich-text",
            name: "body",
            label: "Introduccio llarga",
            isBody: true,
          },
        ],
        ui: {
          router: ({ document }) =>
            document?.permalink ||
            `/gastronomic/receptes/${document._sys.filename}/`,
        },
      },
      {
        name: "actualitat",
        label: "Actualitat Page",
        path: "src/_data/actualitat",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "image",
                name: "backgroundImage",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "backgroundAlt",
                label: "Background Alt Text",
                required: true,
              },
              {
                type: "string",
                name: "tagsTitle",
                label: "Tags Title",
                required: true,
              },
              {
                type: "string",
                name: "tags",
                label: "Tags",
                list: true,
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "filtersBar",
            label: "Filters Bar",
            fields: [
              {
                type: "object",
                name: "items",
                label: "Filter Items",
                list: true,
                required: true,
                fields: [
                  {
                    type: "string",
                    name: "label",
                    label: "Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "type",
                    label: "Type",
                    required: true,
                  },
                  {
                    type: "object",
                    name: "options",
                    label: "Options",
                    list: true,
                    required: true,
                    fields: [
                      {
                        type: "string",
                        name: "label",
                        label: "Label",
                        required: true,
                      },
                      {
                        type: "string",
                        name: "value",
                        label: "Value",
                        required: true,
                      },
                    ],
                  },
                ],
              },
              {
                type: "string",
                name: "resetLabel",
                label: "Reset Label",
                required: true,
              },
              {
                type: "string",
                name: "emptyLabel",
                label: "Empty Results Label",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "loadMoreLabel",
            label: "Load More Label",
            required: true,
          },
          {
            type: "object",
            name: "newsletter",
            label: "Newsletter",
            fields: [
              { type: "string", name: "title", label: "Title", required: true },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "inputLabel",
                label: "Input Label",
                required: true,
              },
              {
                type: "string",
                name: "buttonLabel",
                label: "Button Label",
                required: true,
              },
            ],
          },
        ],
      },
      {
        name: "professionalsInspiration",
        label: "Professionals Inspiration",
        path: "src/_data/professionalsInspiration",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              { type: "string", name: "title", label: "Title", required: true },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "image",
                name: "backgroundImage",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "backgroundAlt",
                label: "Background Alt Text",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "foundationsSection",
            label: "Foundations Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "recipesSection",
            label: "Recipes Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "authorRecipesSection",
            label: "Author Recipes Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "gastronomicRecipes",
        label: "Gastronomic Recipes",
        path: "src/_data/gastronomicRecipes",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              { type: "string", name: "title", label: "Title", required: true },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "image",
                name: "backgroundImage",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "backgroundAlt",
                label: "Background Alt Text",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "filtersBar",
            label: "Filters Bar",
            fields: [
              {
                type: "string",
                name: "items",
                label: "Filter Labels",
                list: true,
                required: true,
              },
              {
                type: "string",
                name: "searchLabel",
                label: "Search Button Label",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "foundationsSection",
            label: "Foundations Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "homeTraditionsSection",
            label: "Home Traditions Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "classicsSection",
            label: "Classics Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "healthySection",
            label: "Healthy Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "sweetSection",
            label: "Sweet Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "remediesSection",
            label: "Remedies Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "home",
        label: "Home Page",
        path: "src/_data",
        format: "json",
        match: {
          include: "home",
        },
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "partnersSection",
            label: "Partners Slider",
            fields: [
              {
                type: "string",
                name: "labelSmall",
                label: "Small Label",
                required: true,
              },
              {
                type: "string",
                name: "titleLine1",
                label: "Title Line 1",
                required: true,
              },
              {
                type: "string",
                name: "titleLine2",
                label: "Title Line 2",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "Button Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "Button Link",
                required: true,
              },
              {
                type: "object",
                name: "partners",
                label: "Partner Logos",
                list: true,
                fields: [
                  {
                    type: "image",
                    name: "src",
                    label: "Logo Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "alt",
                    label: "Alt Text",
                    required: true,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  search: {
    tina: {
      indexerToken: process.env.TINA_SEARCH_TOKEN,
      stopwordLanguages: ["eng", "spa"],
    },
    indexBatchSize: 100,
    maxSearchIndexFieldLength: 100,
  },
});
